name: check-codebase

on:
  push:

jobs:
  check-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun format
      - run: bun lint
