name: check-codebase

on:
  push:
    paths-ignore:
      - tools/**
      - README.md

jobs:
  check-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun check
