name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      
      - run: bun install
      
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify
        env:
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          PROD_SERVICE_URL: ${{ secrets.PROD_SERVICE_URL }}

      # - name: Comment Preview URL
      #   uses: ./.github/actions/comment-preview-url
      #   with:
      #     target_url: ${{ steps.cloudflare-pages-deploy.outputs.deployment-url }}
      #     pr_number: ${{ github.event.number }}
      #   if: github.event_name == 'pull_request'
